image:
  repository: "python"
  tag: 3.8-bullseye
  pullPolicy: Always

service:
  port: 80
  targetPort: 7007

workingDir: /app

initCommand: 
  unzipbuild:
    - sh
    - -c
    - |
        /bin/sh <<'EOF'

        yum install -y unzip
        aws s3 cp s3://{{ .Values.s3.bucket }}/{{ .Values.build.id }}.zip /tmp/{{ .Values.build.id }}.zip
        unzip -o /tmp/{{ .Values.build.id }}.zip -d ./react
        rm /tmp/{{ .Values.build.id }}.zip

        EOF

  buildapp:
    - sh
    - -c
    - |
        /bin/sh <<'EOF'

        cd ./react/node_modules/isolated-vm && npm i

        EOF

appCommand:
  - sh
  - -c
  - |
      /bin/sh <<'EOF'

      cd ./react
      apt update
      
      pip install --upgrade pip
      pip install mkdocs
      pip install mkdocs-techdocs-core

      Xvfb ":42" &

      wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      
      export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      
      nvm install 20

      npm -g install corepack
      corepack enable
      
      node ./packages/backend --config ./app-config.yaml

      EOF