apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-omega
  description: Team Omega
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: manoj.kumar
spec:
  profile:
    displayName: Manoj Kumar
    email: manoj.kumar@admgroup.com 
  memberOf: [team-omega]