name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
pool: Default

trigger: none

variables:
    - group: omega-k8s

resources:
  pipelines:
    - pipeline: build
      source: build ... backstage
      branch: feature/application-inventory-management # env/production
      trigger:
        branches:
          include:
            - feature/application-inventory-management # env/production
  
steps:
  - task: HelmInstaller@1
    displayName: 🧑‍🔧 Install Helm

  - task: HelmDeploy@0
    displayName: "🧑‍🔧 Helm: Chart install or upgrade"
    inputs:
      command: upgrade
      install: true
      connectionType: Kubernetes Service Connection
      kubernetesServiceConnection: $(K8s.ServiceConnection)
      azureContainerRegistry: admomega.azurecr.io
      waitForExecution: false
      chartType: FilePath
      chartPath: $(Build.SourcesDirectory)/.charts/backstage
      releaseName: backstage
      chartVersion: 1.0.0
      namespace: backstage-production
      arguments: >-
        --debug
        --reset-values
        --set tags.app=$(resources.pipeline.build.runID)
        --set environment=production
        -f $(Build.SourcesDirectory)/.charts/backstage/app-config.production.yaml
