apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: admgroup-omega-secrets
spec:
  parameters:
    keyvaultName: admgroup-secrets
    objects: |
      array:
        - |
          objectName: aks-blob-storage-integration-storageaccountname
          objectType: secret
        - |
          objectName: aks-blob-storage-integration-storageaccountkey
          objectType: secret
        - | 
          objectName: certificate-admsolutions-cer
          objectType: secret
        
        - | 
          objectName: certificate-admsolutions-key
          objectType: secret

        - |
          objectName: backstage-bff-kv-clientId
          objectType: secret

        - |
          objectName: backstage-bff-kv-clientSecret
          objectType: secret 

        - |
          objectName: backstage-bff-kv-tenantId
          objectType: secret
      
    {{- include "secretProviderClasses.omegaSecrets.customAuth" . | nindent 4 }}
  provider: azure
  secretObjects:
    - secretName: backstage-aks-build-fileshare
      type: Opaque
      data:
        - key: azurestorageaccountname
          objectName: aks-blob-storage-integration-storageaccountname

        - key: azurestorageaccountkey
          objectName: aks-blob-storage-integration-storageaccountkey

    - secretName: admsolutions-tls
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: certificate-admsolutions-cer
        - key: tls.key
          objectName: certificate-admsolutions-key

    - secretName: keyvault-credentials
      type: Opaque
      data:
        - key: backstage-bff-kv-clientId
          objectName: backstage-bff-kv-clientId
        - key: backstage-bff-kv-clientSecret
          objectName: backstage-bff-kv-clientSecret
        - key: backstage-bff-kv-tenantId
          objectName: backstage-bff-kv-tenantId