apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: backstage-k8s
      initContainers:
        - name: unzipbuild
          image: "amazon/aws-cli:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.workingDir }}
          command: 
            {{- tpl (toYaml .Values.initCommand.unzipbuild) . | nindent 12 }}

          volumeMounts:             
            - name: app
              mountPath: /app

        - name: buildapp
          image: "node:20-bullseye"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.workingDir }}
          command: 
            {{- tpl (toYaml .Values.initCommand.buildapp) . | nindent 12 }}

          volumeMounts:             
            - name: app
              mountPath: /app

      containers:
        - name: k8s-api-proxy
          image: bitnami/kubectl:latest
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          command:
            - kubectl
            - proxy
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.workingDir }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}

          command: 
            {{- tpl (toYaml .Values.appCommand) . | nindent 12 }}

          env: 
            {{- toYaml .Values.appEnv | nindent 12 }}

          volumeMounts:
            - name: app 
              mountPath: /app

      volumes:
        - name: app
          emptyDir:
            sizeLimit: 3Gi 