apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: articles
  description: articles api
  annotations:
    backstage.io/source-location: url:https://dev.azure.com/adm-group/Client%20Frontend/_git/omega-apis?path=/frontoffice/articles&version=GBenv/production&_a=contents
    backstage.io/techdocs-ref: url:https://dev.azure.com/adm-group/Client%20Frontend/_git/omega-apis?version=GBmain&path=/frontoffice/articles/.docs
  tags:
    - minimalapis
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: team-omega
  system: omega
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
