apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cart
  description: cart trigger
  annotations:    
    backstage.io/source-location: url:https://dev.azure.com/adm-group/Client%20Frontend/_git/omega-services?path=/frontoffice/cart&version=GBenv/production&_a=contents
    backstage.io/techdocs-ref: url:https://dev.azure.com/adm-group/Client%20Frontend/_git/omega-services?path=/frontoffice/cart/.docs
  tags:
    - minimalapis
    - dotnet
    - data   
spec:
  type: asyncapi
  lifecycle: production
  owner: team-omega
  system: omega
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json