apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/cors-enabled: "true"
    alb.ingress.kubernetes.io/cors-allow-origin: "*"
    alb.ingress.kubernetes.io/cors-allow-methods: "GET,POST,PUT,DELETE,OPTIONS"
    alb.ingress.kubernetes.io/cors-allow-headers: "*"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: backstage
spec:
  ingressClassName: alb
  rules:
  - host: {{ include "app.host" . }}
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 80
        path: /
        pathType: Prefix

  - host: backstage1.northeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 80
        path: /
        pathType: Prefix

  tls:
  - hosts:
    - {{ include "app.host" . }}
    secretName: admsolutions-tls
