kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-k8s-reader
rules:
- apiGroups: 
  - "*"
  resources:
    - namespaces
    - secretproviderclasses
    - deployments
    - pods/log
    - configmaps
    - services
    - pods
    - ingresses
    - replicasets
    - statefulsets
    - cronjobs
    - jobs
    - events
  verbs:
    - get
    - list
    - watch