apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalogues
  description: catalogues component
  annotations:
    dev.azure.com/project: Client Frontend
    dev.azure.com/build-definition: omega-frontoffice-api-catalogues-build
  tags:
    - minimalapis
    - dotnet
    - data   
spec:
  type: service
  lifecycle: development
  owner: team-omega
  system: omega
  subcomponentOf: frontoffice
  providesApis:
    - catalogues